name: Manual publish (Sheets → GitHub)

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sheet-publish
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create google-service-account.json
        run: printf '%s' "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > google-service-account.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm install

      - name: Run manual gate script
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node perplexity-sheet-to-github.js

      - name: Commit docs/ if changed
        run: |
          set -euo pipefail
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if [ -n "$(git status --porcelain docs)" ]; then
            git add docs
            git commit -m "Update website (docs) [skip ci]"
            git pull --rebase origin main || true
            git push origin HEAD:main
          else
            echo "No changes in docs/"
          fi
